### PR TITLE
Fix to read grib files obeying 'resolutionAndComponentFlags'

### PR DESCRIPTION
**Pull request by tpowellmeto**
This fix allows iris to obey the 'resolutionAndComponentFlags' value within GRIB files. This value specifies whether iris should be looking for i/j increments within the given GRIB file, and if they aren't specified (value of 0 is set) provides a method of calculating the increments via other means.

### CODE REVIEW

**Comment by tpowellmeto** [comment]
@bjlittle not sure if you spotted this but it would be useful for our project to get it pulled in :)

**Comment by bjlittle** [comment]
Hey @tpowellmeto, thanks for the PR!

Sorry, I missed this - spinning way too many plates (unsuccessfully).

We're aiming to cut an `iris-grib` version `0.15.0` very soon, so it would be lovely to include this to unblock you guys.

I'll get to this asap, promise :wink:

**Comment by tpowellmeto** [comment]
no problem @lbdreyer, those license issues should now be resolved 👍

**Comment by lbdreyer** [comment]
Thanks @tpowellmeto !

**Pull request merged**
