### PR TITLE
Travis tests

### PR DESCRIPTION
**Pull request by pp-mo**
Attempt to enable testing in Travis.
I dropped nosetests requirement for now as I don't know of a need for it, and it makes this slightly simpler.

### CODE REVIEW

**Comment by rhattersley** [comment]
Rebase?

**Comment by pp-mo** [comment]
Rebased, testing
(but probably needs a sqwish)

**Comment by pp-mo** [comment]
Now working, rebased + sqwished.

NOTE: it now downloads iris-test-data in Travis.
I think this is worth doing, so we can quickly migrate existing tests from Iris to here.

**Comment by rhattersley** [comment]
:+1: for getting them working, but wow, that's a lot of noise from a single test! :scream:

**Pull request merged**
