### PR TITLE
Add support for Lambert Conformal saving

### PR DESCRIPTION
**Pull request by djkirkham**
No tests yet, will add them shortly.

False eastings/northings are not supported for Lambert Conformal in GRIB, so they are ignored on save. Doing this doesn't lose any information about the locations of the points though, since GRIB stores the longitude and latitude of the first point in the grid.

### CODE REVIEW

**Comment by djkirkham** [comment]
Thinking about it, it's probably worth at least having a warning that the false eastings/northings won't be saved.

**Comment by lbdreyer** [comment]
It might be worth adding a loader for Lambert Conformal at the same time. Then you can check what happens when you load in and save out a Lambert Conformal, and compare that to the original.

**Comment by djkirkham** [comment]
@lbdreyer There already is a loader. It saves the correct values in the file, but the issue is with saving and then loading, where the false eastings/northings are lost. I'm not sure if this should be considered a problem.

**Comment by djkirkham** [comment]
I still haven't added testing code, so don't merge yet

**Comment by marqh** [comment]
@djkirkham any further tests planned, or is this good to go from your point of view?

**Comment by djkirkham** [comment]
@marq It's ready to be merged from my point of view

**Comment by marqh** [comment]
I am also happy with this

thank you @djkirkham

**Pull request merged**
