### PR TITLE
Code qa refresh

### PR DESCRIPTION
**Pull request by pp-mo**
Replaces #564 

Don't understand why this was needed, since the branch location is the same.
Seems like GitHub got confused somehow by my adding a commit + then removing it

### CODE REVIEW

**Review by ukmo-ccbunney — APPROVED** [review]
As per your other PR, this looks good.
Remember to raise an issue for the ignored numpydoc tests.

**Review by ukmo-ccbunney — CHANGES_REQUESTED** [review]
Actually - jsut spotted one thing:

`ruff-pre-commit` hook is now version 0.7.4, you've got it as 0.7.3

Can you update?

**Comment by pp-mo** [comment]
> `ruff-pre-commit` hook is now version 0.7.4, you've got it as 0.7.3

Just added in a[ re-ordering of the pre-commit hooks to match the current template order](https://github.com/SciTools/iris-grib/pull/568/commits/0e537c3d843d8435211c79ca0320ba1004c9d22a).

**Comment by ukmo-ccbunney** [comment]
> > `ruff-pre-commit` hook is now version 0.7.4, you've got it as 0.7.3
> 
> Just added in a[ re-ordering of the pre-commit hooks to match the current template order](https://github.com/SciTools/iris-grib/pull/568/commits/0e537c3d843d8435211c79ca0320ba1004c9d22a).

You are still running on 0.7.3 for Ruff though.

**Comment by pp-mo** [comment]
> You are still running on 0.7.3 for Ruff though.

Sorry, missed including that somehow!

**Comment by ukmo-ccbunney** [comment]
I wonder if rather than setting `strict=false` in your `[tools.mypy]` section, it would be better to set `strict=true` and capture all the failing error codes?

For iris-grib, this would require the following ignores in the pyproject.toml:

```
strict = true 
disable_error_code =  [
    "arg-type",
    "assignment",
    "attr-defined",
    "index",
    "misc",
    "name-defined",
    "no-untyped-call",
    "no-untyped-def",
    "override",
    "type-arg",
    "union-attr",
    "var-annotated",
]
```

These can then all be added to a new issue documenting the failing mypy tests for iris-grib?

What do you think?

**Comment by pp-mo** [comment]
> I wonder if rather than setting `strict=false` in your `[tools.mypy]` section, it would be better to set `strict=true` and capture all the failing error codes?
> ... What do you think?

Well, here's one way of looking at what that does ...
```
$ mypy . --no-color-output | grep -oE "\[.*\]$" errs.txt | sort | uniq -c
      2 [<type>, <type>] = ...")  [var-annotated]
      2 [<type>] = ...")  [var-annotated]
     13 [Any, Any] | list[Any] | None" has no attribute "append"  [union-attr]
      2 [Any, Any] | list[Any] | None" is not indexable  [index]
     13 [Any, Any]" of "dict[Any, Any] | list[Any] | None" has no attribute "append"  [union-attr]
      1 [Any, Any]", variable has type "tuple[Any]")  [assignment]
      9 [Any, None]"; expected "tuple[Any, int]"  [arg-type]
      1 [Any]")  [index]
      1 [Any]", variable has type "tuple[Any, ...]")  [assignment]
      1 [Any]", variable has type "tuple[Any, Any]")  [assignment]
      1 [GenericConcreteGRIBCode]" has no attribute "argnames"  [attr-defined]
      1 [[Any, Any, Any, Any, Any], Any]" has no attribute "assert_called_once_with"  [attr-defined]
      1 [[Any, Any, Any, Any, Any], Any]" has no attribute "assert_called_with"  [attr-defined]
      1 [[Any, Any, Any, Any], Any]" has no attribute "assert_called_once_with"  [attr-defined]
      1 [[Any, Any], Any]" has no attribute "assert_called_with"  [attr-defined]
      1 [[Any], Any]" has no attribute "assert_called_with"  [attr-defined]
      1 [[Any], Any]" has no attribute "call_count"  [attr-defined]
      3 [assignment]
    191 [attr-defined]
      2 [index]
     15 [misc]
     12 [name-defined]
   1421 [no-untyped-call]
    964 [no-untyped-def]
      3 [override]
      1 [str] | None" has no attribute "groups"  [union-attr]
      1 [str]", variable has type "bytes")  [assignment]
      1 [str]", variable has type "type[int]")  [assignment]
      5 [type-arg]
     15 [var-annotated]
```

**Comment by pp-mo** [comment]
> I wonder if rather than setting `strict=false` in your `[tools.mypy]` section, it would be better to set `strict=true` and capture all the failing error codes?

See https://github.com/SciTools/iris-grib/pull/568/commits/cdb78f53619953e41587b2868aa8ac3a80ee1143

**Review by ukmo-ccbunney — APPROVED** [review]
OK. I think we're good to go.

**Comment by pp-mo** [comment]
Brilliant, thanks @ukmo-ccbunney !!

To complete this work : 
 * [ ] Small follow-up coming to rationalise the toml content
 * some issues for future removal of "ignores" 
   * [ ] ruff 
   * [ ] mypy 
   * [ ] numpydocs

**Pull request merged**
