### PR TITLE
NEP 29 changes - py39 minimum

### PR DESCRIPTION
**Pull request by trexfeathers**
[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)

### CODE REVIEW

**Comment by trexfeathers** [comment]
Updating the lock files seems to have brought along some minor printing changes affecting CML tests...

**Comment by pp-mo** [comment]
> Updating the lock files seems to have brought along some minor printing changes affecting CML tests...

I think that problem has been outstanding since https://github.com/SciTools/iris-grib/pull/334
At that time, we had a problem because iris-grib tests against **_both_** latest-main and latest-release Iris, and they had different behaviour.
But, since the changes have now appeared in a release, I think it should now be OK to update all the test results.
I was going to get around to it sometime, honest!

**Comment by trexfeathers** [comment]
I've eyeballed the CML changes and they do seem to correspond to SciTools/iris#5235

**Review by pp-mo — APPROVED** [review]
Looks OK !

**Comment by trexfeathers** [comment]
Thanks @pp-mo!

**Pull request merged**
