### PR TITLE
updated translations

### PR DESCRIPTION
**Pull request by marqh**
new translations and changed translations from metarelate

### CODE REVIEW

**Comment by marqh** [comment]
@lbdreyer i have updated this

**Comment by marqh** [comment]
@lbdreyer please consider merging 
https://github.com/SciTools/iris/pull/2198
first, to preserve repeatability

thank you

**Comment by marqh** [comment]
hmmm, there are test failures quite a way away from where I am working, they seem connected to the test running, using iris master but not iris 1.9:

```
https://travis-ci.org/SciTools/iris-grib/jobs/167670573#L606
```
https://travis-ci.org/SciTools/iris-grib/jobs/167670573#L606

I am quite confused
@bjlittle @lbdreyer any clues??

**Comment by lbdreyer** [comment]
Differences in the conda environments, between the test that's passing :white_check_mark: and that's failing :x:

package| :white_check_mark:iris=1.9 | :x:  iris_from_source=master, iris_grib=1.14.7
------------ | -------------|-------------
iris_grib |0.9.0 pip installed|0.9.0 conda-forge
python ecmwf grib| 1.15.0|1.14.7
ecmwf_grib|1.15.0|1.14.7
nc_time_axis| none | 1.0.0
iris|1.9.2 conda-forge|1.11.0.dev0 pip installed

**Comment by lbdreyer** [comment]
It is now getting iris-grib from scitools. Surely it should be pip installing iris-grib?

**Comment by bjlittle** [comment]
@marqh Awesome work! Thanks! :+1:

**Pull request merged**
