### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by pp-mo**
Following @trexfeathers comment [here](https://github.com/SciTools/iris-grib/issues/280#issuecomment-873882751)

Various references to 'master' branch remaining in README

### CODE REVIEW

**Review by trexfeathers — APPROVED** [review]

**Comment by trexfeathers** [comment]
Is this failure related to the fact that there are references to Iris `master` in the Nox file?

**Comment by pp-mo** [comment]
> Is this failure related to the fact that there are references to Iris master in the Nox file?

Maybe ...
Let's try https://github.com/SciTools/iris-grib/pull/282

**Comment by pp-mo** [comment]
> > Is this failure related to the fact that there are references to Iris master in the Nox file?
> Maybe ...
> Let's try #282

None of that.  It's because we were testing with Python 3.6 by default, and Iris is no longer supporting that.

Unfortunately, it's not the only problem, as the Py3.7 tests show.
We were also using the routine 'iris.util._array_slice_ifempty`, which [we removed from Iris, but no longer needed due to changes in iris._lazy_data]().

Will address in #282 (which I'm going to rename)

**Comment by pp-mo** [comment]
> Will address in #282 (which I'm going to rename)

Now in #283
I think this one should wait for that..

**Pull request merged**
