### PR TITLE
Hybrid coords round trip

### PR DESCRIPTION
**Pull request by corinnebosley**
Round-trip integration tests for hybrid height and hybrid pressure.

Also a small fix for a bit that was forgotten and only revealed in these tests.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@dkillick @pp-mo Should I put in some bits at the end of each test to delete the saved files?

**Comment by pp-mo** [comment]
"Otherwise" LGTM :+1:  -- short, but if it works that's already proving quite a lot.
Sorry, meant to create a proper review but pressed wrong button.

**Comment by corinnebosley** [comment]
@pp-mo Thanks for that, useful pointers, especially the temp_filepath pattern that I didn't know about before.  Cool.

**Comment by corinnebosley** [comment]
Wait a minute though, I still need to delete the save directories that I had before...

**Comment by corinnebosley** [comment]
@pp-mo @dkillick @kaedonkers Tests now passing.  Any more tweaks?

**Comment by pp-mo** [comment]
> Any more tweaks?

Maybe just a comment to say that/why it is loading+save a separate reference cube.

I'm also interested in your `save(... saver='grib2')` usage as I didn't know it could do that ! 
The docstrings as-is suggest it can only be a saver *function*.
Obviously that's is an Iris issue...

**Comment by corinnebosley** [comment]
@pp-mo Yeah I didn't know you could do that either, it was a bit of guesswork that got lucky because the docs are really really vague.

**Comment by corinnebosley** [comment]
@pp-mo Thanks!

**Pull request merged**
