### PR TITLE
0.14.x mergeback onto master

### PR DESCRIPTION
**Pull request by lbdreyer**
A mergeback has not been done since the 0.14.1 release and so the changes included in #149 needs to be merged back onto master

### CODE REVIEW

**Comment by lbdreyer** [comment]
@pp-mo are you available to have a look at this?

**Comment by lbdreyer** [comment]
Closes #168

**Comment by pp-mo** [comment]
Thanks @lbdreyer 
Looking at this, it has only 2 commits.
  * the [first commit](https://github.com/SciTools/iris-grib/pull/169/commits/9446e083968b4198b7eebc08b95daa068b661b97) removes workarounds :  all looks fine
  * the [second commit](https://github.com/SciTools/iris-grib/pull/169/commits/17664b55a48a1e3953db91273e9bd1d7e4bee957) pins eccodes version, **which I think will simply conflict with #166**

So I would recommend waiting until #166, then we just use the first commit.
**Unless** you think we need a complete merge-back to enable future developments on 0.14.x ???

**Comment by lbdreyer** [comment]
> So I would recommend waiting until #166, then we just use the first commit.
Unless you think we need a complete merge-back to enable future developments on 0.14.x ???

Happy with this :)
I don't believe a complete merge-back is necessary for 0.14.x dev.

**Comment by pp-mo** [comment]
Hi @lbdreyer 
Since #166 this should be ok, but it needs 
  1. a rebase and 
  2. include only the first of 2 commits, as discussed.

**Comment by lbdreyer** [comment]
Thanks @pp-mo! I have now updated this such that it only includes the first commit

**Comment by lbdreyer** [comment]
I have now resolved the conflicts. Just need the tests to pass then this can go in!

**Pull request merged**
