### PR TITLE
Added in linkchecks and coverage checks for gha ci

### LINKED ISSUE #340: Migrate from Cirrus CI to GitHub Actions
For alignment with the rest of SciTools

**both tests and doctests**, please!
```[tasklist]
### Tasks  (attempt : drop if tricky)
- [ ] https://github.com/SciTools/iris-grib/issues/277
- [ ] https://github.com/SciTools/iris-grib/issues/417
```

### PR DESCRIPTION
**Pull request by ESadek-MO**
Closes #340.
Finishes work started in #415.

### CODE REVIEW

**Comment by ESadek-MO** [comment]
Readded in a couple of links to be ignored:

https://software.ecmwf.int/ is no longer correct, https://confluence.ecmwf.int/ is, however it doesn't seem to have a landing page for GRIB.

I'm ignoring any errors in release notes atm, as it seems questionable to maintain that, but that might want to be discussed.

**Review by stephenworsley — APPROVED** [review]
Looks good.

**Comment by stephenworsley** [comment]
@bjlittle Is it just not running in the CI at all then? I've had coverage problems in iris-esmf-regrid also, but they've been causing CI failures.

**Comment by bjlittle** [comment]
Seems like the `--coverage` flag is passed into nox from the GHA, but then nothing is done with it.

**Comment by bjlittle** [comment]
Also, if it was working, `codecov` would add comments to the pr.

I suspect tokens require to be also configured.

**Comment by pp-mo** [comment]
> Also, if it was working, `codecov` would add comments to the pr.
> 
> I suspect tokens require to be also configured.

Not sure I follow exactly (I'm a bit rusty on this), but I think we can get around to this in due course.
**Can you please create a follow-on issue explaining what needs doing here ?**

**Pull request merged**
