### PR TITLE
Initial upgrade to "Code QA Sprint" standards

### PR DESCRIPTION
**Pull request by pp-mo**
Updated pre-commit config, to be compared with recommendations in ["Scitools Code Quality Bonanza" project](https://github.com/orgs/SciTools/projects/43)

### CODE REVIEW

**Comment by pp-mo** [comment]
### TODO 
Heads-up for what isn't here, to be addressed next (or ruled out-of-scope for the Code-QA sprint project) :
  * additional [disabled numpydocs-validation checks](https://github.com/SciTools/iris-grib/blob/8d341f23783b3e4e26e3f9cb223fa3f466e78d78/pyproject.toml#L226-L235) :  remove some, where straightforward, with matching source changes
  * temporary disables in [`./.ruff.toml`](https://github.com/SciTools/iris-grib/blob/5a1f8588e2e71827892bf5ee0e8d28f6f3305596/.ruff.toml) : see if we can target some of these

**Comment by pp-mo** [comment]
Rebased following update for dependabot changes.
I think rebased is easier to look at.
Anyway, you should consider the last commit separately @ukmo-ccbunney (!)

**Review by ukmo-ccbunney — COMMENTED** [review]
The changes from this commit (d6d581e) all look very sensible. 👍

**Review by ukmo-ccbunney — APPROVED** [review]
Changes look good to me. 👍
Don't forget to raise an issue for the ignored mypy tests (there will probably be a lot more once `[tool.mypy] strict = True`?

**Comment by pp-mo** [comment]
Something odd here.  I removed the temporary ["Wild renames"](https://github.com/SciTools/iris-grib/pull/564/commits/729ba138828b1f7cde3d65cbfa0c15140a401689) commit from the branch on my fork, but Github doesn't pick up the 'backwards change', for some odd reason.
So close + reopen to see it it fixes

**Comment by pp-mo** [comment]
Something odd here. I removed the temporary ["Wild renames"](https://github.com/SciTools/iris-grib/pull/564/commits/729ba138828b1f7cde3d65cbfa0c15140a401689) commit from the branch on my fork, but Github doesn't pick up the 'backwards change', for some odd reason.
So close + reopen to see it it fixes

**Pull request closed without merging**
